# Generated by Django 4.0.3 on 2022-03-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechType',
            new_name='Shoe',
        ),
        migrations.AlterModelTable(
            name='shoe',
            table='Shoe',
        ),
    ]
