# Generated by Django 4.0.3 on 2022-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoes', '0002_rename_techtype_shoe_alter_shoe_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productur1',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='producturl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
